# Site settings
title: On Demand Software
email: enrico.papi@gmail.com
url: https://enricop.github.io
description: "Papi Enrico"
skills: "Sistemi Embedded - HMI - Networking - Data Analysis"
meta_author: Papi Enrico

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Enrico Papi
  location: Forlì-Cesena
  social: <a href="https://angel.co/enricop">Angels List</a>
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: http://stackoverflow.com/users/1970960/enricop
  - title: bitbucket
    url: http://bitbucket.org/enricop
  - title: github
    url: http://github.com/enricop

# Postal address (add as many lines as necessary)
address:
  - line: Forlì-Cesena, Italy

# Credits content
credits: 'Software developer'

# Build settings
markdown: kramdown
permalink: pretty
